using Microsoft.EntityFrameworkCore;
using SnippetManager.Data;
using SnippetManager.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Windows;
using System.Windows.Controls;
using System.Configuration;
using SnippetManager.ViewModels;
using SnippetManager.Dtos;
using OpenFileDialog = Microsoft.Win32.OpenFileDialog;
using SaveFileDialog = Microsoft.Win32.SaveFileDialog;
using System.Diagnostics;

namespace SnippetManager
{
    /// <summary>
    /// Interaction logic for Dashboard.xaml
    /// </summary>
    public partial class Dashboard : UserControl
    {
        private readonly codexDBContext _context;

        public Dashboard()
        {
            InitializeComponent();
            Debug.WriteLine("Dashboard initialized.");

            // added to resolve issues caused by older dependencies relying on ApplicationDbContext.
            // Transitioning to codexDBContext, which aligns with the current database schema generated by EF Core Power Tools.
            // Explicit configuration of codexDBContext ensures proper database connection and avoids conflicts.
            // The connection string is dynamically fetched from the configuration file for flexibility and security.
            var optionsBuilder = new DbContextOptionsBuilder<codexDBContext>();
            var connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            optionsBuilder.UseSqlServer(connectionString);
            _context = new codexDBContext(optionsBuilder.Options);
            Debug.WriteLine("Database context initialized.");

            LoadCategories();
            LoadSnippets();
        }

        private void LoadCategories()
        {
            Debug.WriteLine("Loading categories...");
            // Load languages 
            var languages = _context.Categories.Where(c => c.Type == "Language").ToList();
            foreach (var language in languages)
            {
                LanguagesListBox.Items.Add(language.Name);
                Debug.WriteLine($"Loaded language: {language.Name}");
            }

            // Load tags
            var tags = _context.Categories.Where(c => c.Type == "Tag").ToList();
            foreach (var tag in tags)
            {
                TagsListBox.Items.Add(tag.Name);
                Debug.WriteLine($"Loaded tag: {tag.Name}");
            }
        }

        private void LoadSnippets()
        {
            Debug.WriteLine("Loading snippets...");
            if (MainViewModel.CurrentUser != null)
            {
                int currentUserId = MainViewModel.CurrentUser.UserId; // Assuming UserId is the primary key for the User model
                Debug.WriteLine($"Current user ID: {currentUserId}");

                var snippets = _context.Snippets
                    .Include(s => s.Category) // Include related Category
                    .Where(s => s.UserId == currentUserId)
                    .ToList()
                    .Select(s => new SnippetViewModel { Snippet = s })
                    .ToList();
                SnippetsDataGrid.ItemsSource = snippets; // Bind the list of snippets to the DataGrid
                Debug.WriteLine($"Loaded {snippets.Count} snippets for user ID {currentUserId}.");
            }
            else
            {
                MessageBox.Show("No user is currently logged in.");
                Debug.WriteLine("No user is currently logged in.");
            }
        }



        private void AddTagButton_Click(object sender, RoutedEventArgs e)
        {
            string newTag = TagInputTextBox.Text;
            Debug.WriteLine($"Adding new tag: {newTag}");

            // Add the new tag to the TagsListBox if it is not empty
            if (!string.IsNullOrWhiteSpace(newTag))
            {
                TagsListBox.Items.Add(newTag);
                TagInputTextBox.Clear();
                Debug.WriteLine($"Added tag to list: {newTag}");

                // Save the tag to the Categories table
                var category = new Category { Name = newTag, Type = "Tag" };
                _context.Categories.Add(category);
                _context.SaveChanges();
                Debug.WriteLine($"Saved new tag to database: {newTag}");
            }
        }

        private void AddLanguageButton_Click(object sender, RoutedEventArgs e)
        {
            string newLanguage = LanguageInputTextBox.Text;
            Debug.WriteLine($"Adding new language: {newLanguage}");

            // Add the new language to the LanguagesListBox if it is not empty
            if (!string.IsNullOrWhiteSpace(newLanguage))
            {
                LanguagesListBox.Items.Add(newLanguage);
                LanguageInputTextBox.Clear();
                Debug.WriteLine($"Added language to list: {newLanguage}");

                // Save the language to the Categories table
                var category = new Category { Name = newLanguage, Type = "Language" };
                _context.Categories.Add(category);
                _context.SaveChanges();
                Debug.WriteLine($"Saved new language to database: {newLanguage}");
            }
        }

        private void NewSnippetButton_Click(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine("Creating new snippet...");
            var optionsBuilder = new DbContextOptionsBuilder<codexDBContext>();
            var connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            optionsBuilder.UseSqlServer(connectionString);

            // Pass the configured context to CreateSnippet
            CreateSnippet createSnippetWindow = new CreateSnippet(new codexDBContext(optionsBuilder.Options));

            // Show the window
            createSnippetWindow.Show();
            Debug.WriteLine("New snippet window shown.");
        }

        private void NewSettingsButton_Click(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine("Opening settings...");
            Settings createSettingsWindow = new Settings();

            createSettingsWindow.Show();
            Debug.WriteLine("Settings window shown.");
        }

        private void ImportButton_Click(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine("Importing snippets...");
            OpenFileDialog openFileDialog = new OpenFileDialog
            {
                Filter = "JSON files (*.json)|*.json|All files (*.*)|*.*"
            };

            if (openFileDialog.ShowDialog() == true)
            {
                string filePath = openFileDialog.FileName;
                Debug.WriteLine($"Selected file for import: {filePath}");
                string json = File.ReadAllText(filePath);
                var options = new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true,
                    WriteIndented = true
                };
                var snippetDtos = JsonSerializer.Deserialize<List<SnippetDto>>(json, options);

                if (snippetDtos != null)
                {
                    foreach (var snippetDto in snippetDtos)
                    {
                        var newSnippet = new Snippet
                        {
                            UserId = MainViewModel.CurrentUser.UserId,
                            Title = snippetDto.Title,
                            Description = snippetDto.Description,
                            Language = snippetDto.Language,
                            Tags = snippetDto.Tags,
                            Content = snippetDto.Content,
                            CreatedAt = DateTime.Now,
                            UpdatedAt = DateTime.Now
                        };

                        _context.Snippets.Add(newSnippet);
                        Debug.WriteLine($"Added new snippet: {newSnippet.Title}");
                    }
                    _context.SaveChanges();
                    LoadSnippets();
                    MessageBox.Show("Snippets imported successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                    Debug.WriteLine("Snippets imported and saved to database.");
                }
                else
                {
                    MessageBox.Show("No snippets found in the file.", "Error", MessageBoxButton.OK, MessageBoxImage.Error);
                    Debug.WriteLine("No snippets found in the file.");
                }
            }
        }




        private void ExportButton_Click(object sender, RoutedEventArgs e)
        {
            Debug.WriteLine("Exporting snippets...");
            SaveFileDialog saveFileDialog = new SaveFileDialog
            {
                Filter = "JSON files (*.json)|*.json|All files (*.*)|*.*"
            };

            if (saveFileDialog.ShowDialog() == true)
            {
                string filePath = saveFileDialog.FileName;
                Debug.WriteLine($"Selected file for export: {filePath}");
                var selectedSnippets = ((List<SnippetViewModel>)SnippetsDataGrid.ItemsSource)
                    .Where(s => s.IsSelected)
                    .Select(s => new SnippetDto
                    {
                        Title = s.Snippet.Title,
                        Description = s.Snippet.Description,
                        Language = s.Snippet.Language,
                        Tags = s.Snippet.Tags,
                        Content = s.Snippet.Content
                    })
                    .ToList();
                var options = new JsonSerializerOptions
                {
                    WriteIndented = true
                };
                string json = JsonSerializer.Serialize(selectedSnippets, options);
                File.WriteAllText(filePath, json);
                MessageBox.Show("Selected snippets exported successfully.", "Success", MessageBoxButton.OK, MessageBoxImage.Information);
                Debug.WriteLine("Selected snippets exported to file.");
            }
        }





        private void SelectAllCheckBox_Click(object sender, RoutedEventArgs e)
        {
            if (sender is CheckBox selectAllCheckBox)
            {
                bool isChecked = selectAllCheckBox.IsChecked ?? false;
                Debug.WriteLine($"Select All checkbox changed to: {isChecked}");
                foreach (var snippet in SnippetsDataGrid.Items)
                {
                    if (snippet is SnippetViewModel snippetItem)
                    {
                        snippetItem.IsSelected = isChecked;
                    }
                }
                SnippetsDataGrid.Items.Refresh();
            }
        }

        private void IndividualCheckBox_Click(object sender, RoutedEventArgs e)
        {
            if (sender is CheckBox checkBox && checkBox.DataContext is SnippetViewModel snippetViewModel)
            {
                snippetViewModel.IsSelected = checkBox.IsChecked ?? false;
                Debug.WriteLine($"Snippet '{snippetViewModel.Snippet.Title}' selection changed to: {snippetViewModel.IsSelected}");
            }
        }


    }
}
