// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SnippetManager.Models;

public partial class Snippet
{
    public int SnippetId { get; set; }

    public int UserId { get; set; }

    public int? CategoryId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Language { get; set; }

    public string Tags { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Category Category { get; set; }

    public virtual User User { get; set; }
}